name: E2E Tests
on:
  push:
    branches:
      - main
      - maintenance
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Dependencies
        run: npm ci
      - name: Install Node-RED Dependencies
        working-directory: ./cypress/fixtures/user-dir/
        run: npm install
      - name: Run Linting Tests
        run: npm run lint
      - name: Run Dashboard E2E (Cypress) Tests
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v7.4.1
        with:
          install: false
          config-file: cypress.config.js
          build: npm run build
          start: npm run cy:server
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: cypress-output
          path: |
            cypress/screenshots
            cypress/videos